name: Deploy MuleSoft Application

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build Application
        run: mvn clean install

      - name: Deploy to CloudHub
        env:
          ANYPOINT_CLIENT_ID: ${{secrets.ANYPOINT_CLIENT_ID}}
          ANYPOINT_CLIENT_SECRET: ${{secrets.ANYPOINT_CLIENT_SECRET}}
        run: mvn clean deploy -DmuleDeploy -Dclient_id=$ANYPOINT_CLIENT_ID -Dclient_secret=$ANYPOINT_CLIENT_SECRET -X -e
